database:
  connection: mongodb://localhost:27017
  database: local
  ordersCollection: orders
  productsCollection: products
    
rabbit_mq:
  user:
  password:
  host: localhost
  port: 5672
  exchange:
    name: order
    kind: direct
  
keycloak:
  url: http://localhost:8080
  realm: users
