services:
  sql_server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: users_db
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_PID=Developer
      - SA_PASSWORD=${USERS_PASS}
    ports:
      - 1433:1433
    restart: always
    volumes:
      - sql_server_data:/var/opt/mssql

  rabbit_mq:
    image: rabbitmq:4.2.0-management
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBIT_MQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBIT_MQ_PASS}
    ports:
      - 5672:5672
      - 15672:15672

  keycloak:
    image: quay.io/keycloak/keycloak:26.4
    environment:
      - KEYCLOAK_ADMIN=${KEYCLOAK_ADMIN}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASS}
    command: start-dev
    ports:
      - 8080:8080
    volumes:
      - keycloak_data:/opt/keycloak/data

  mailpit:
    image: axllent/mailpit:v1.29
    restart: unless-stopped
    volumes:
      - ./data:/data
    ports:
      - 8025:8025
      - 1025:1025
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATABASE: /data/mailpit.db
      MP_SMTP_AUTH: ${MAILPIT_USER}:${MAILPIT_PASS}
      MP_SMTP_AUTH_ALLOW_INSECURE: 1

  mongo_db:
    image: mongo:7.0.13-rc0
    container_name: orders_db
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongodb-data:/data/db

  postgres:
    image: postgres:14.22
    container_name: invoices_db
    environment:
      POSTGRES_USER: ${INVOICES_USER}
      POSTGRES_PASSWORD: ${INVOICES_PASS}
      POSTGRES_DB: ${INVOICES_DB}
    ports:
      - 5432:5432
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  sql_server_data:
  keycloak_data:
  mongodb-data:
  postgres_data: